#!/bin/bash

export NUM_LAYERS=16
export HIDDEN_SIZE=1536
export NUM_ATTN_HEADS=16
export SEQ_LEN=1024

export FMOE_FASTER_GLBPLC_ALPHA="2"
export FMOE_FASTER_GLBPLC_DMODEL=${HIDDEN_SIZE}

export dense_name=GPT-L${NUM_LAYERS}-H${HIDDEN_SIZE}-ATTN${NUM_ATTN_HEADS}-SEQ${SEQ_LEN}-ALPHA${FMOE_FASTER_GLBPLC_ALPHA}